image:
  name: docker:git

services:
  - docker:18.09.7-dind

stages:
  - release

release_job:
  stage: release
  only:
    - tags
  script:
    - apk update && apk add --no-cache build-base cargo gcc libffi-dev libressl-dev musl-dev openssl-dev python3 python3-dev py3-pip
    - pip3 install twine wheel
    - rm -rf build dist *.egg-info
    - python3 setup.py sdist bdist_wheel
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python3 -m twine upload --verbose --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
