---
# Run Flake8 linter.
repos:
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    additional_dependencies: [flake8-bugbear]

# Run unit tests with Pytest.
- repo: local
  hooks:
  - id: tests
    name: tests
    entry: poetry run pytest
    language: system
    types: [python]
    pass_filenames: false

# Type check code with MyPy.
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v0.931'
  hooks:
  - id: mypy
    additional_dependencies: [types-click, types-pkg-resources, types-PyYAML]
